### ISSUE TITLE
Use Transactable instead?

### ISSUE THREAD

**Issue by bkuhlmann** [a-chris/to-result#1]
Hello. :wave: I'm not sure this is an "issue" in the truest sense of the word but wasn't sure where to log this information. Anyway, in looking over this gem, you might want to take a look at the [Transactable](https://www.alchemists.io/projects/transactable) gem since it's -- sort of -- in the same spirit of what you are trying to do here but with whole lot of bells and whistles. Most importantly, the *Transactable* gem gives you away in which to leverage the *Railway Pattern* as a series of steps which is a little easier to read using a condensed DSL.

**Comment by a-chris** [comment]
ehi @bkuhlmann I'm delighted to get an issue from you, your collection of gems is impressive 🔥
coincidentally, I've read about Transactable a few days ago but I cannot use that gem because at my job we've fully embraced the dry ecosystem with `dry-monads` as the most used gem, we are used to its syntax and I really could not get to introduce it to new project.
thanks for the suggestion anyway, I will try to use Transactable for my next side project and I'd love to take inspiration from your gem for a few new features 😁

**Comment by bkuhlmann** [comment]
Ha, thanks, that collection is over a decade of work and evolution. 😊 

It's nice to hear you are building top Dry Monads and Dry RB at large. I do want to point out that *Transactable* IS built upon Dry Monads. In some sense it's a supercharged version of Dry Monads so you can do more with less. Anyway, if you are headed down the Dry RB path, Transactable would give you additional super powers.

You can close this issue if you like but mostly wanted to raise a warning flag, so-to-speak, that you might be headed down a path of duplicated effort. :wink:
